main: net.arkube.blackswords.BlackSwords
name: BlackSword
version: 0.1
commands:
    blackcraft:
        description: Commande de craft rapide.
    rank:
        description: Commande réservé aux Administrateur!
    monnaie:
        description: Commande réservé aux Administrateur!
    craft:
        description: Ouvre un inventaire de craft!
    repair:
        description: Repare l'item dans ta main!